### ISSUE TITLE
Add SSNO as param on Get-Cardholder

### ISSUE THREAD

**Issue by bpfoley45** [erwindevreugd/PSDataConduIT#49]
I often need to query a cardholder based on the SSNO field and found that this attribute can be queried from the Lnl_Cardholder class. 

Can the function be updated to include the param and if clause? testing showed that I needed to quote the variable as shown below in the process block: 

       if($SSNO) {
            $query += " AND SSNO='$SSNO'"
        }

**Comment by erwindevreugd** [comment]
Yes it can, thank you! I've made the change (and also added Firstname, Lastname and Email parameters) to Get-Cardholder. The changes are on the dev branch.
Let me know if this works for you and if you have any more suggestions!

**Comment by bpfoley45** [comment]
looks good; I am also following along in dev channel and testing
